### ISSUE TITLE
Flickr can't find a valid callback URL.

### ISSUE THREAD

**Issue by myhd** [hugoh/Offlickr2#4]
On first use, Offlickr2 needs to be authorized with Flickr.

The URL is something like http://flickr.com/services/auth/?api_key=xxxxxxxxxx&perms=read&frob=&api_sig=xxxxxxxx.

In any case, I will always see a page that says "Oops! Flickr can't find a valid callback URL. An external application has requested your login credentials and permission to perform certain actions on your behalf, but has failed to include all the required data."

**Comment by hugoh** [comment]
I'm wondering if this was caused by an older phpFlickr version. Is it still an issue?

**Comment by dmd** [comment]
I'm still getting this.

**Comment by hugoh** [comment]
I think that this is because phpFlickr uses Flickr Auth and not OAuth. I need to review this, but that may mean adding OAuth support to phpFlickr.

**Comment by k0a1a** [comment]
yes, OAuth seems to be the cause here,
thanks

**Comment by hugoh** [comment]
Version 1.5 should fix the problem.
